language: php
php:
    - '7.4'

before_script:
    - composer install --dev --no-interaction

script:
    - mkdir -p build/logs
    - php ./vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - travis_retry php ./vendor/bin/php-coveralls -v

notifications:
    email:
        - kustov.vitalik@gmail.com